import { CartProvider } from "@/pages/CartContext";
import "@/devlink/global.css";
import { DevLinkProvider } from "@/devlink/DevLinkProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DevLinkProvider>
          <CartProvider>
          {children}
          </CartProvider>
        </DevLinkProvider>
      </body>
    </html>
  );
}
